x1<-rnorm(150,mean = 100, sd = 15)
par(mfrow=c(3,1))
hist(x1, freq = FALSE, breaks = 20)
points(density(x1), type = "l")
rug(x1)
library(vioplot)
library(sm)
vioplot(x1, horizontal=TRUE, col="gray")
boxplot(x1, horizontal=TRUE)
par(mfrow=c(1,1))
qqnorm(x1)
qqline(x1)
library(ggplot2)
df <- data.frame(x1)
p <- ggplot(df, aes(sample = x1))
p <- p + stat_qq()
print(p)
par(mfrow=c(1,1))
library(carData)
library(car)
qqPlot(x1, las =1, id = list(n = 6, cex =1), lwd = 1, main="QQ Plot")
x2 <- runif(150, min = 50, max = 150)
par(mfrow=c(3,1))
hist(x2, freq = FALSE, breaks = 20)
points(density(x2), type = "l")
rug(x2)
library(vioplot)
vioplot(x2, horizontal=TRUE, col="gray")
boxplot(x2, horizontal=TRUE)
par(mfrow=c(1,1))
qqPlot(x2, las =1, id = list(n = 6, cex =1), lwd = 1, main="QQ Plot")
x3.temp <- rnorm(150, mean = 0, sd = 1)
x3 <- sign(x3.temp)*x3.temp^2 * 15 + 100
par(mfrow=c(3,1))
hist(x3, freq = FALSE, breaks = 20)
points(density(x3), type = "l")
rug(x3)
library(vioplot)
vioplot(x3, horizontal=TRUE, col="gray")
boxplot(x3, horizontal=TRUE)
par(mfrow=c(1,1))
qqPlot(x3, las =1, id = list(n = 0, cex =1), lwd = 1, main="QQ Plot")
x4 <- rexp(150, rate = 1)
par(mfrow=c(3,1))
hist(x4, freq = FALSE, breaks = 20)
points(density(x4), type = "l")
rug(x4)
library(vioplot)
vioplot(x4, horizontal=TRUE, col="gray")
boxplot(x4, horizontal=TRUE)
par(mfrow=c(1,1))
qqPlot(x4, las =1, id = list(n = 0, cex =1), lwd = 1, main="QQ Plot")
x5 <- 15 - rexp(150, rate = 0.5)
par(mfrow=c(3,1))
hist(x5, freq = FALSE, breaks = 20)
points(density(x5), type = "l")
rug(x5)
library(vioplot)
vioplot(x5, horizontal=TRUE, col="gray")
boxplot(x5, horizontal=TRUE)
par(mfrow=c(1,1))
qqPlot(x5, las =1, id = list(n = 0, cex =1), lwd = 1, main="QQ Plot")
shapiro.test(x1)
library(nortest)
ad.test(x1)
cvm.test(x1)
shapiro.test(x2)
library(nortest)
ad.test(x2)
cvm.test(x2)
shapiro.test(x3)
library(nortest)
ad.test(x3)
cvm.test(x3)
shapiro.test(x4)
library(nortest)
ad.test(x4)
cvm.test(x4)
shapiro.test(x5)
library(nortest)
ad.test(x5)
cvm.test(x5)
a <- c( 0.7, -1.6, -0.2, -1.2, 0.1, 3.4, 3.7, 0.8, 0.0, 2.0)
b <- c( 1.9, 0.8, 1.1, 0.1, -0.1, 4.4, 5.5, 1.6, 4.6, 3.0)
d <- b - a
sleep <- data.frame(a, b, d)
shapiro.test(sleep$d[0:5000])
library(nortest)
ad.test(sleep$d)
cvm.test(sleep$d)
par(mfrow=c(3,1))
hist(sleep$d, freq = FALSE, breaks = 20)
points(density(sleep$d), type = "l")
rug(sleep$d)
library(vioplot)
vioplot(sleep$d, horizontal=TRUE, col="gray")
boxplot(sleep$d, horizontal=TRUE)
par(mfrow=c(1,1))
qqPlot(sleep$d, las =1, id = list(n = 4, cex =1), lwd = 1, main="QQ Plot")

men <- c(217, 123, 80, 140, 115, 135, 59, 126, 70, 63,
         147, 122, 108, 70)
women <- c( 84, 87, 77, 84, 73, 66, 70, 35, 77, 73,
            56, 112, 56, 84, 80, 101, 66, 84)
level <- c(men, women)
sex <- c(rep("men", length(men)), rep("women", length(women)))
andro <- data.frame(level, sex)
library(ggplot2)
p1 <- ggplot(andro, aes(x = sex, y = level, fill=sex))
p1 <- p1 + geom_boxplot()
p1 <- p1 + stat_summary(fun = mean, geom = "point", shape = 3, size = 2)
p1 <- p1 + labs(title = "Androstenedione Levels in Diabetics")
shapiro.test(men)
library(nortest)
ad.test(men)
cvm.test(men)
shapiro.test(women)
library(nortest)
ad.test(women)
cvm.test(women)
p2 <- ggplot(andro, aes(x = level, fill=sex))
p2 <- p2 + geom_histogram(binwidth = 20, alpha = 0.5, position="identity")
p2 <- p2 + labs(title = "Androstenedione Levels in Diabetics")
library(gridExtra)
grid.arrange(p1, p2, ncol=1)
par(mfrow=c(2,1))
qqPlot(men, las =1, id = list(n = 0, cex =1), lwd = 1, main="QQ Plot")
qqPlot(women, las =1, id = list(n = 0, cex =1), lwd = 1, main="QQ Plot")
n = 10
r = 5
norm.many <- data.frame(id = rep(seq(1:r^2), n) , x = rnorm(r^2 * n))
library(ggplot2)
p <- ggplot(norm.many, aes(x = x))
p <- p + geom_histogram(binwidth = 0.4)
p <- p + facet_wrap(~ id, ncol = r)
p <- p + labs(title = "Twenty-five samples of size n=10 from a Normal(0,l) distribution")
print(p)

n = 30
r = 5
norm.many <- data.frame(id = rep(seq(1:r^2), n), x = rnorm(r^2 * n))
library(ggplot2)
p <- ggplot(norm.many, aes(x = x))
p <- p + geom_histogram(binwidth = 0.4)
p <- p + facet_wrap(~ id, ncol = r)
p <- p + labs(title = "Twenty-five samples of size n=30 from a Normal(0,l) distribution")
print(p)

c(mean(men), mean(women), sd(men), sd(women))
c(IQR(men), IQR(women), length(men), length(women))
bartlett.test(level ~ sex, data = andro)
library(car)
leveneTest(level ~ sex, data = andro)
fligner.test(level ~ sex, data = andro)

